### PR TITLE
[#31, irods/irods#5712, irods/irods#6106, irods/irods#6211] Update for first round of reorganization changes

### LINKED ISSUE #31: nlohmann-json-related compilation failure
When compiling main, I get the following compilation error:
```
In file included from /usr/irods_capability_publishing/plugin_specific_configuration.cpp:3:
In file included from /usr/include/irods/irods_server_properties.hpp:7:
In file included from /usr/include/irods/irods_configuration_parser.hpp:19:
In file included from /opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:51:
In file included from /opt/irods-externals/json3.6.1-0/include/nlohmann/adl_serializer.hpp:5:
/opt/irods-externals/json3.6.1-0/include/nlohmann/detail/conversions/from_json.hpp:298:55: error: no matching member function for call to 'get'
    p = {j.at(0).template get<A1>(), j.at(1).template get<A2>()};
                                     ~~~~~~~~~~~~~~~~~^~~~~~~
/opt/irods-externals/json3.6.1-0/include/nlohmann/detail/conversions/from_json.hpp:358:16: note: in instantiation of function template specialization 'nlohmann::detail::from_json<nlohmann::basic_json<>, const std::string, boost::any>' requested here
        return from_json(j, val);
               ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/adl_serializer.hpp:28:9: note: in instantiation of function template specialization 'nlohmann::detail::from_json_fn::operator()<nlohmann::basic_json<>, std::pair<const std::string, boost::any>>' requested here
        ::nlohmann::from_json(std::forward<BasicJsonType>(j), val);
        ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2595:36: note: in instantiation of function template specialization 'nlohmann::adl_serializer<std::pair<const std::string, boost::any>>::from_json<const nlohmann::basic_json<> &, std::pair<const std::string, boost::any>>' requested here
        JSONSerializer<ValueType>::from_json(*this, ret);
                                   ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/detail/conversions/from_json.hpp:191:27: note: in instantiation of function template specialization 'nlohmann::basic_json<>::get<std::pair<const std::string, boost::any>, std::pair<const std::string, boost::any>, 0>' requested here
        return i.template get<typename ConstructibleArrayType::value_type>();
                          ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/detail/conversions/from_json.hpp:230:5: note: in instantiation of function template specialization 'nlohmann::detail::from_json_array_impl<nlohmann::basic_json<>, std::unordered_map<std::string, boost::any>>' requested here
    from_json_array_impl(j, arr, priority_tag<3> {});
    ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/detail/conversions/from_json.hpp:358:16: note: in instantiation of function template specialization 'nlohmann::detail::from_json<nlohmann::basic_json<>, std::unordered_map<std::string, boost::any>, 0>' requested here
        return from_json(j, val);
               ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/adl_serializer.hpp:28:9: note: in instantiation of function template specialization 'nlohmann::detail::from_json_fn::operator()<nlohmann::basic_json<>, std::unordered_map<std::string, boost::any>>' requested here
        ::nlohmann::from_json(std::forward<BasicJsonType>(j), val);
        ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2595:36: note: in instantiation of function template specialization 'nlohmann::adl_serializer<std::unordered_map<std::string, boost::any>>::from_json<const nlohmann::basic_json<> &, std::unordered_map<std::string, boost::any>>' requested here
        JSONSerializer<ValueType>::from_json(*this, ret);
                                   ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2875:16: note: in instantiation of function template specialization 'nlohmann::basic_json<>::get<std::unordered_map<std::string, boost::any>, std::unordered_map<std::string, boost::any>, 0>' requested here
        return get<ValueType>();
               ^
/usr/irods_capability_publishing/plugin_specific_configuration.cpp:20:36: note: in instantiation of function template specialization 'nlohmann::basic_json<>::operator unordered_map<std::unordered_map<std::string, boost::any>, 0>' requested here
                            return rule_engine.at(CFG_PLUGIN_SPECIFIC_CONFIGURATION_KW);
                                   ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2510:16: note: candidate template ignored: requirement 'std::is_same<boost::any, nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, adl_serializer>>::value' was not satisfied [with BasicJsonType = boost::any]
    basic_json get() const
               ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2533:19: note: candidate template ignored: requirement 'detail::is_basic_json<boost::any>::value' was not satisfied [with BasicJsonType = boost::any]
    BasicJsonType get() const
                  ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2583:15: note: candidate template ignored: requirement 'detail::has_from_json<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, adl_serializer>, boost::any, void>::value' was not satisfied [with ValueTypeCV = boost::any, ValueType = boost::any]
    ValueType get() const noexcept(noexcept(
              ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2634:15: note: candidate template ignored: requirement 'detail::has_non_default_from_json<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, adl_serializer>, boost::any, void>::value' was not satisfied [with ValueTypeCV = boost::any, ValueType = boost::any]
    ValueType get() const noexcept(noexcept(
              ^
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2764:10: note: candidate template ignored: substitution failure [with PointerType = boost::any]: no matching member function for call to 'get_ptr'
    auto get() noexcept -> decltype(std::declval<basic_json_t&>().template get_ptr<PointerType>())
         ^                                                                 ~~~~~~~
/opt/irods-externals/json3.6.1-0/include/nlohmann/json.hpp:2776:20: note: candidate template ignored: substitution failure [with PointerType = boost::any]: no matching member function for call to 'get_ptr'
    constexpr auto get() const noexcept -> decltype(std::declval<const basic_json_t&>().template get_ptr<PointerType>())
                   ^                                                                             ~~~~~~~
```

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Companion PR for irods/irods#6201
Closes irods/irods#5712 for this repo.
In service of irods/irods#6106 and irods/irods#6211.
Also fixes #31

### CODE REVIEW

File: configuration.cpp [hunk 1]
```diff
@@ -1,6 +1,9 @@
 
 #include "configuration.hpp"
 #include "plugin_specific_configuration.hpp"
+#include "fmt/format.h"
```
Comment (korydraughn) [inline configuration.cpp:4]: angle brackets?

**Review by alanking — APPROVED** [review]
